name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      # Set up Node.js for frontend
      - name: Set up Node.js (Frontend)
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'MConnect/frontend/package-lock.json'
      
      # Install and build frontend
      - name: Install and build frontend
        working-directory: MConnect/frontend
        run: |
          npm ci
          npm run build

      # Set up Node.js for backend
      - name: Set up Node.js (Backend)
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: 'MConnect/backend/package-lock.json'
      
      # Install backend dependencies
      - name: Install backend dependencies
        working-directory: MConnect/backend
        run: npm ci

      # Deploy to Azure Static Web Apps
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_WATER_009A21E00 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "MConnect/frontend/build"
          app_build_command: "cd MConnect/frontend && npm ci && npm run build"
          output_location: ""  # Empty because we're pointing directly to the build folder
          api_location: "MConnect/backend"
          skip_app_build: true

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_WATER_009A21E00 }}
          action: "close"

